import 'package:garden_app_ui/model/category_model.dart';

List<PlantModel> plants = [
  PlantModel(
    imagePath: 'assets/images/1.png',
    name: 'Indoor Fern',
    price: '200',
    description: 'A perennial herbaceous plant with soft, green stems.',
    category: 'Indoor',
  ),
  PlantModel(
    imagePath: 'assets/images/2.png',
    name: 'Outdoor Fern',
    price: '150',
    description: 'A perennial herbaceous plant that thrives outdoors.',
    category: 'Outdoor',
  ),
  PlantModel(
    imagePath: 'assets/images/3.png',
    name: 'Indoor Ivy',
    price: '250',
    description: 'An evergreen perennial ideal for indoor environments.',
    category: 'Indoor',
  ),
  PlantModel(
    imagePath: 'assets/images/4.png',
    name: 'Outdoor Ivy',
    price: '180',
    description: 'An evergreen perennial suitable for outdoor spaces.',
    category: 'Outdoor',
  ),
  PlantModel(
    imagePath: 'assets/images/2.png',
    name: 'Thallophyta Algae',
    price: '220',
    description: 'A simple plant belonging to the Thallophyta category.',
    category: 'Thallophyta',
  ),
  PlantModel(
    imagePath: 'assets/images/1.png',
    name: 'Bryophyta Moss',
    price: '160',
    description: 'A small, non-vascular plant in the Bryophyta group.',
    category: 'Bryophyta',
  ),
  PlantModel(
    imagePath: 'assets/images/1.png',
    name: 'Indoor Succulent',
    price: '300',
    description: 'A hardy, low-maintenance plant perfect for indoors.',
    category: 'Indoor',
  ),
  PlantModel(
    imagePath: 'assets/images/2.png',
    name: 'Outdoor Succulent',
    price: '220',
    description: 'A hardy plant that thrives in outdoor conditions.',
    category: 'Outdoor',
  ),
  PlantModel(
    imagePath: 'assets/images/3.png',
    name: 'Indoor Cactus',
    price: '350',
    description: 'A resilient, water-efficient plant for indoor settings.',
    category: 'Indoor',
  ),
  PlantModel(
    imagePath: 'assets/images/4.png',
    name: 'Outdoor Cactus',
    price: '250',
    description: 'A resilient plant that does well in outdoor environments.',
    category: 'Outdoor',
  ),
  PlantModel(
    imagePath: 'assets/images/2.png',
    name: 'Thallophyta Fungi',
    price: '200',
    description: 'A simple organism belonging to the Thallophyta category.',
    category: 'Thallophyta',
  ),
  PlantModel(
    imagePath: 'assets/images/1.png',
    name: 'Bryophyta Liverwort',
    price: '180',
    description: 'A non-vascular plant in the Bryophyta group.',
    category: 'Bryophyta',
  ),
  PlantModel(
    imagePath: 'assets/images/1.png',
    name: 'Indoor Bamboo',
    price: '400',
    description: 'A fast-growing plant ideal for indoor decoration.',
    category: 'Indoor',
  ),
  PlantModel(
    imagePath: 'assets/images/2.png',
    name: 'Outdoor Bamboo',
    price: '350',
    description: 'A robust plant that grows quickly outdoors.',
    category: 'Outdoor',
  ),
  PlantModel(
    imagePath: 'assets/images/3.png',
    name: 'Indoor Palm',
    price: '450',
    description: 'A tropical plant that thrives indoors.',
    category: 'Indoor',
  ),
  PlantModel(
    imagePath: 'assets/images/4.png',
    name: 'Outdoor Palm',
    price: '400',
    description: 'A tropical plant suited for outdoor conditions.',
    category: 'Outdoor',
  ),
  PlantModel(
    imagePath: 'assets/images/2.png',
    name: 'Thallophyta Lichen',
    price: '220',
    description: 'A composite organism belonging to Thallophyta.',
    category: 'Thallophyta',
  ),
  PlantModel(
    imagePath: 'assets/images/1.png',
    name: 'Bryophyta Hornwort',
    price: '200',
    description: 'A small, non-vascular plant in the Bryophyta category.',
    category: 'Bryophyta',
  ),
  PlantModel(
    imagePath: 'assets/images/1.png',
    name: 'Indoor Orchid',
    price: '500',
    description: 'An elegant flowering plant for indoor spaces.',
    category: 'Indoor',
  ),
  PlantModel(
    imagePath: 'assets/images/2.png',
    name: 'Outdoor Orchid',
    price: '450',
    description: 'An elegant flowering plant that thrives outdoors.',
    category: 'Outdoor',
  ),
];
