import 'package:garden_app_ui/model/category_model.dart';

List<PlantModel> plants = [
  PlantModel(
    imagePath: 'assets/images/plant1.jpg',
    name: 'Indoor Fern',
    price: '200',
    description:
        'Flamingo flowers are tropical plants native to South America, known for their vibrant red, heart-shaped flowers, which are actually modified leaves called spathes. The true flowers are tiny and grow on a stalk called the spadix, which protrudes from the center of the spathe Flamingo flowers come in a variety of colors, including pink, white, and purple, but red is the most common.,',
    category: 'Indoor',
  ),
  PlantModel(
    imagePath: 'assets/images/plant2.jpg',
    name: 'Outdoor Fern',
    price: '150',
    description: 'A perennial herbaceous plant that thrives outdoors.',
    category: 'Outdoor',
  ),
  PlantModel(
    imagePath: 'assets/images/plant3.jpg',
    name: 'Indoor Ivy',
    price: '250',
    description: 'An evergreen perennial ideal for indoor environments.',
    category: 'Indoor',
  ),
  PlantModel(
    imagePath: 'assets/images/plant4.jpg',
    name: 'Outdoor Ivy',
    price: '180',
    description: 'An evergreen perennial suitable for outdoor spaces.',
    category: 'Outdoor',
  ),
  PlantModel(
    imagePath: 'assets/images/plant5.jpg',
    name: 'Thallophyta Algae',
    price: '220',
    description: 'A simple plant belonging to the Thallophyta category.',
    category: 'Thallophyta',
  ),
  PlantModel(
    imagePath: 'assets/images/plant6.jpg',
    name: 'Bryophyta Moss',
    price: '160',
    description: 'A small, non-vascular plant in the Bryophyta group.',
    category: 'Bryophyta',
  ),
  PlantModel(
    imagePath: 'assets/images/plant7.jpg',
    name: 'Indoor Succulent',
    price: '300',
    description: 'A hardy, low-maintenance plant perfect for indoors.',
    category: 'Indoor',
  ),
  PlantModel(
    imagePath: 'assets/images/plant8.jpg',
    name: 'Outdoor Succulent',
    price: '220',
    description: 'A hardy plant that thrives in outdoor conditions.',
    category: 'Outdoor',
  ),
  PlantModel(
    imagePath: 'assets/images/plant9.jpg',
    name: 'Outdoor Cactus',
    price: '250',
    description: 'A resilient plant that does well in outdoor environments.',
    category: 'Outdoor',
  ),
  PlantModel(
    imagePath: 'assets/images/plant10.jpg',
    name: 'Thallophyta Fungi',
    price: '200',
    description: 'A simple organism belonging to the Thallophyta category.',
    category: 'Thallophyta',
  ),
  PlantModel(
    imagePath: 'assets/images/plant11.jpg',
    name: 'Bryophyta Liverwort',
    price: '180',
    description: 'A non-vascular plant in the Bryophyta group.',
    category: 'Bryophyta',
  ),
  PlantModel(
    imagePath: 'assets/images/plant12.jpg',
    name: 'Indoor Bamboo',
    price: '400',
    description: 'A fast-growing plant ideal for indoor decoration.',
    category: 'Indoor',
  ),
  PlantModel(
    imagePath: 'assets/images/plant13.jpg',
    name: 'Outdoor Bamboo',
    price: '350',
    description: 'A robust plant that grows quickly outdoors.',
    category: 'Outdoor',
  ),
  PlantModel(
    imagePath: 'assets/images/plant14.jpg',
    name: 'Indoor Palm',
    price: '450',
    description: 'A tropical plant that thrives indoors.',
    category: 'Indoor',
  ),
  PlantModel(
    imagePath: 'assets/images/plant15.jpg',
    name: 'Outdoor Palm',
    price: '400',
    description: 'A tropical plant suited for outdoor conditions.',
    category: 'Outdoor',
  ),
  PlantModel(
    imagePath: 'assets/images/plant16.jpg',
    name: 'Thallophyta Lichen',
    price: '220',
    description: 'A composite organism belonging to Thallophyta.',
    category: 'Thallophyta',
  ),
  PlantModel(
    imagePath: 'assets/images/plant17.jpg',
    name: 'Bryophyta Hornwort',
    price: '200',
    description: 'A small, non-vascular plant in the Bryophyta category.',
    category: 'Bryophyta',
  ),
  PlantModel(
    imagePath: 'assets/images/plant18.jpg',
    name: 'Indoor Orchid',
    price: '500',
    description: 'An elegant flowering plant for indoor spaces.',
    category: 'Indoor',
  ),
  PlantModel(
    imagePath: 'assets/images/plant19.jpg',
    name: 'Outdoor Orchid',
    price: '450',
    description: 'An elegant flowering plant that thrives outdoors.',
    category: 'Outdoor',
  ),
  PlantModel(
    imagePath: 'assets/images/plant20.jpg',
    name: 'Indoor Cactus',
    price: '350',
    description: 'A resilient, water-efficient plant for indoor settings.',
    category: 'Indoor',
  ),
];
